### ISSUE TITLE
Are there any documents related to this package?

### ISSUE THREAD

**Issue by hengzhe-zhang** [eustomaqua/PyEnsemble#1]
This is a wonderful package. However, I cannot find any usage documents. In my scenario, I want to find a package that can prune my random forest. Therefore, I hope this package can provide a general algorithm which can prune any list of trees. Can this package achieve this target? If it can, how can I use this package?

**Comment by eustomaqua** [comment]
So sorry for just noticing this issue @hengzhe-zhang 
I didn't include documents in this repo and adding documents is a plan but I cannot guarantee how long it will take yet. Perhaps you could find the examples in the `tests` folder helpful to understand their usage at present.

To answer your question, if you are thinking of pruning one specific tree, then no, the pruning methods used in this repo are not able to change the structure of one trained decision tree. However, if you are thinking of pruning a random forest that includes many trees, then yes, you may achieve your goal by treating the members of your random forest separately and using their predictions to do that. 

I will give you an example to ease the understanding. If the shape of their predictions is (number of individual classifiers, number of instances in the dataset) and the predictions are represented in one matrix, that is `yt`. Meanwhile, the true labels of the instances are represented as one vector, that is `y`, with the shape of (number of instances,). 

You may use any pruning methods like this:
```python
# name_pru could be anyone in the `AVAILABLE_NAME_PRUNE`
# that is located in "pyensemble/pruning/__init__.py"
from pyensemble.pruning.overall import existing_contrastive_pruning_method

yo, P, flag = existing_contrastive_pruning_method(name_pru, yt, y, nb_cls, nb_pru)
# nb_cls is the number of individual classifiers
# nb_pru is the number of individual ones in the pruned sub-ensemble, which you could decide on your own
```

I guess this could answer your question, unless you have more. In that case, please do not hesitate to let me know. Hope you find this useful and wish you the best for your work!
